### PR TITLE
update r-densityclust

### PR DESCRIPTION
**Pull request by daler**
Required to update `bioconductor-monocle` in bioconda.

### CODE REVIEW

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by daler** [comment]
ping @ocefpaf

**Comment by ocefpaf** [comment]
@daler I am not a maintainer here. Please address the @conda-forge/r-densityclust team. If they do not answer then you can ask the core members for help. But it seems that @bgruening is already on it.

**Comment by bgruening** [comment]
Thanks @daler!
I will go through my mails this evening and get to the rest.

**Comment by daler** [comment]
Thanks!

**Pull request merged**
